from time import time

''' 
Problem 45: https://projecteuler.net/problem=45

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
               Triangle 	  	     Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
               Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
               Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T(285) = P(165) = H(143) = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

def main():
     T = lambda n: n * (n + 1) // 2
     P = lambda n: n * (3 * n - 1) // 2
     H = lambda n: n * (2 * n - 1)
     t = set(T(i) for i in range(100000))
     p = set(P(i) for i in range(100000))
     h = set(H(i) for i in range(100000))
     k = t.intersection(p)
     return list(k.intersection(h))[3]


if __name__=="__main__":    
     start = time()
     print(f"\nAnswer: { main() }")
     print(f"Time Taken: { time() - start }\n")
     